-- Auto-generated by build_papers.py -- do not edit
import DependencyGraph
import Paper1IT.Entropy
import Paper1IT.GraphEntropy
import Paper1IT.GraphEntropyAsymptotic

#export_decl_info_json "decls.json"
