"""
Constants for OpenHCS.

This module exports all constants defined in the constants submodules.
"""

# These imports are re-exported through __all__
from openhcs.constants.clauses import Clause
from openhcs.constants.constants import (  # Backend constants; Memory constants; I/O constants; Pipeline constants; Default constants
    CPU_MEMORY_TYPES, DEFAULT_ASSEMBLER_LOG_LEVEL, DEFAULT_BACKEND,
    DEFAULT_CPU_THREAD_COUNT, DEFAULT_GROUP_BY, DEFAULT_IMAGE_EXTENSION,
    DEFAULT_IMAGE_EXTENSIONS, DEFAULT_INTERPOLATION_MODE,
    DEFAULT_INTERPOLATION_ORDER, DEFAULT_MARGIN_RATIO, DEFAULT_MAX_SHIFT,
    DEFAULT_MICROSCOPE, DEFAULT_NUM_WORKERS, DEFAULT_OUT_DIR_SUFFIX, DEFAULT_PIXEL_SIZE,
    DEFAULT_POSITIONS_DIR_SUFFIX, DEFAULT_RECURSIVE_PATTERN_SEARCH,
    DEFAULT_SITE_PADDING, DEFAULT_STITCHED_DIR_SUFFIX, DEFAULT_TILE_OVERLAP,
    DEFAULT_VARIABLE_COMPONENTS, FORCE_DISK_WRITE,
    GPU_MEMORY_TYPES, MEMORY_TYPE_CUPY, MEMORY_TYPE_JAX, MEMORY_TYPE_NUMPY,
    MEMORY_TYPE_TENSORFLOW, MEMORY_TYPE_TORCH, READ_BACKEND,
    REQUIRES_DISK_READ, REQUIRES_DISK_WRITE, SUPPORTED_MEMORY_TYPES,
    VALID_GPU_MEMORY_TYPES, VALID_MEMORY_TYPES, WRITE_BACKEND, Backend,
    GroupBy, MemoryType, Microscope, VariableComponents)

__all__ = [
    # Clauses
    'Clause',

    # Backends
    'Backend', 'DEFAULT_BACKEND', 'REQUIRES_DISK_READ', 'REQUIRES_DISK_WRITE',
    'FORCE_DISK_WRITE', 'READ_BACKEND', 'WRITE_BACKEND',

    # Memory
    'MemoryType', 'CPU_MEMORY_TYPES', 'GPU_MEMORY_TYPES', 'SUPPORTED_MEMORY_TYPES',
    'MEMORY_TYPE_NUMPY', 'MEMORY_TYPE_CUPY', 'MEMORY_TYPE_TORCH', 'MEMORY_TYPE_TENSORFLOW',
    'MEMORY_TYPE_JAX', 'VALID_MEMORY_TYPES', 'VALID_GPU_MEMORY_TYPES',

    # I/O
    'DEFAULT_IMAGE_EXTENSION', 'DEFAULT_IMAGE_EXTENSIONS', 'DEFAULT_SITE_PADDING',
    'DEFAULT_RECURSIVE_PATTERN_SEARCH', 'DEFAULT_VARIABLE_COMPONENTS', 'DEFAULT_GROUP_BY',
    'GroupBy', 'VariableComponents', 'Microscope', 'DEFAULT_MICROSCOPE',

    # Pipeline
    'DEFAULT_NUM_WORKERS', 'DEFAULT_OUT_DIR_SUFFIX',
    'DEFAULT_POSITIONS_DIR_SUFFIX', 'DEFAULT_STITCHED_DIR_SUFFIX',

    # Defaults
    'DEFAULT_TILE_OVERLAP', 'DEFAULT_MAX_SHIFT', 'DEFAULT_MARGIN_RATIO',
    'DEFAULT_PIXEL_SIZE', 'DEFAULT_ASSEMBLER_LOG_LEVEL',
    'DEFAULT_INTERPOLATION_MODE', 'DEFAULT_INTERPOLATION_ORDER', 'DEFAULT_CPU_THREAD_COUNT'
]
