-- Paper 1: Typing Discipline proofs
import abstract_class_system
import axis_framework
import context_formalization
import discipline_migration
import java_instantiation
import lwd_converse
import nominal_resolution
import python_instantiation
import rust_instantiation
import typescript_instantiation
