<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>OpenHCS-Windows-Installer</AssemblyName>
    <RootNamespace>OpenHCS.Installer</RootNamespace>
    <ApplicationIcon>OpenHCS.ico</ApplicationIcon>
    <LangVersion>latest</LangVersion>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Install-OpenHCS.ps1">
      <LogicalName>OpenHCS.Installer.Install-OpenHCS.ps1</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="OpenHCS.ico">
      <LogicalName>OpenHCS.Installer.OpenHCS.ico</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\installer_contract.json">
      <LogicalName>OpenHCS.Installer.installer_contract.json</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
