<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>Install-OpenHCS</AssemblyName>
    <RootNamespace>OpenHCS.Installer</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
