"""Typed helpers for OpenHCS step editor ObjectState scopes."""

from __future__ import annotations

import re
from dataclasses import dataclass

from openhcs.core.steps.function_step import FunctionStep
from pyqt_reactive.services.function_navigation import (
    FUNCTION_FIELD_ROOT,
    build_function_token_field_path,
    is_function_field_path,
)
from pyqt_reactive.services.scope_token_service import ScopeTokenService

SCOPE_SEGMENT_SEPARATOR = "::"
FUNCTION_STEP_SCOPE_TOKEN_PREFIX = f"{FunctionStep.__name__.lower()}_"

_SCOPE_SEPARATOR_PATTERN = re.escape(SCOPE_SEGMENT_SEPARATOR)
_FUNCTION_STEP_TOKEN_PATTERN = re.compile(
    rf"^{re.escape(FUNCTION_STEP_SCOPE_TOKEN_PREFIX)}(?P<index>\d+)$"
)
_STEP_EDITOR_SCOPE_PATTERN = re.compile(
    rf"^.*{_SCOPE_SEPARATOR_PATTERN}"
    rf"{re.escape(FUNCTION_STEP_SCOPE_TOKEN_PREFIX)}\d+"
    rf"(?:{_SCOPE_SEPARATOR_PATTERN}[^:]+)?$"
)


@dataclass(frozen=True, slots=True)
class FunctionStepScopeToken:
    """Parsed FunctionStep token generated by ScopeTokenService."""

    raw: str
    index: int

    @classmethod
    def from_segment(cls, segment: str) -> "FunctionStepScopeToken | None":
        match = _FUNCTION_STEP_TOKEN_PATTERN.fullmatch(segment)
        if match is None:
            return None
        return cls(raw=segment, index=int(match.group("index")))


@dataclass(frozen=True, slots=True)
class StepEditorScope:
    """Parsed identity for a step/function editor scope."""

    scope_id: str
    plate_scope: str
    step_scope_id: str
    step_token: FunctionStepScopeToken
    child_scope_id: str | None

    @property
    def is_function_scope(self) -> bool:
        return self.child_scope_id is not None

    @property
    def window_scope_id(self) -> str:
        """Return the WindowManager scope that owns this editor scope."""
        return self.step_scope_id

    def window_field_path(self, field_path: str | None) -> str | None:
        """Map this ObjectState scope field to the parent editor field path."""
        if self.child_scope_id is None or field_path is None:
            return field_path
        if is_function_field_path(field_path):
            target_path = field_path
        else:
            target_path = f"{FUNCTION_FIELD_ROOT}.{field_path}"
        return build_function_token_field_path(
            self.child_scope_id,
            fallback_base_field_path=target_path,
        )

    @classmethod
    def parse(cls, scope_id: str) -> "StepEditorScope":
        segments = tuple(scope_id.split(SCOPE_SEGMENT_SEPARATOR))
        step_ref = cls._step_token_ref(segments)
        if step_ref is None:
            raise ValueError(f"Invalid step scope_id format: {scope_id}")

        step_token_index, step_token = step_ref
        plate_scope = SCOPE_SEGMENT_SEPARATOR.join(segments[:step_token_index])
        step_scope_id = SCOPE_SEGMENT_SEPARATOR.join(segments[: step_token_index + 1])
        child_segments = segments[step_token_index + 1 :]
        return cls(
            scope_id=scope_id,
            plate_scope=plate_scope,
            step_scope_id=step_scope_id,
            step_token=step_token,
            child_scope_id=(
                SCOPE_SEGMENT_SEPARATOR.join(child_segments)
                if child_segments
                else None
            ),
        )

    @classmethod
    def handler_pattern(cls) -> str:
        """Return the WindowFactory pattern for all step editor scopes."""
        return _STEP_EDITOR_SCOPE_PATTERN.pattern

    @classmethod
    def window_scope_id_for_scope(cls, scope_id: str) -> str:
        """Resolve any step editor ObjectState scope to its window scope."""
        return cls.parse(scope_id).window_scope_id

    @classmethod
    def window_field_path_for_scope(
        cls,
        scope_id: str,
        field_path: str | None,
    ) -> str | None:
        """Resolve a scope field path to the editor window navigation path."""
        return cls.parse(scope_id).window_field_path(field_path)

    @staticmethod
    def _step_token_ref(
        segments: tuple[str, ...],
    ) -> "tuple[int, FunctionStepScopeToken] | None":
        for index, segment in enumerate(segments):
            step_token = FunctionStepScopeToken.from_segment(segment)
            if step_token is not None and index > 0:
                return index, step_token
        return None


def build_step_scope_id(plate_scope: str, step: FunctionStep) -> str:
    """Build the ObjectState scope for a FunctionStep under a logical plate scope."""
    return ScopeTokenService.build_scope_id(plate_scope, step)
