-- Auto-generated by scripts/build_papers.py. Do not edit manually.
-- Dependency bridge imports to inline transitive proof machinery.

namespace Ssot

-- Marker module: importing this namespace also imports dependency roots.

end Ssot
