-- Auto-generated by scripts/build_papers.py. Do not edit manually.
-- Dependency bridge imports to inline transitive proof machinery.
import Paper1IT
import AbstractClassSystem
import CrossPaperDependencies
import DeclInfoExport
import DependencyGraph
import GraphExport
import HandleAliases
import Paper1
import Ssot

namespace DecisionQuotient

-- Marker module: importing this namespace also imports dependency roots.

end DecisionQuotient
