import DecisionQuotient.Physics.ObserverRelativeState
import DecisionQuotient.ThermodynamicLift
import DecisionQuotient.IntegrityCompetence
import Mathlib.Data.Real.Basic
import Mathlib.Tactic

/-!
# Physical Conversation Layer

This module keeps conversation formalization inside the same physical stack:

- recurrent circuits sharing one channel node,
- real-to-discrete clamping as the decision operator,
- bounded-channel observability (observer-relative quotient),
- thermodynamic lower bound for clamp events,
- YES/NO/ABSTAIN report surface mapped to typed-report machinery.
-/

namespace DecisionQuotient
namespace Physics
namespace Conversation

open ObserverRelativeState
open DecisionQuotient.ThermodynamicLift
open DecisionQuotient.IntegrityCompetence

universe u v w

/-! ## Recurrent coupled circuits -/

/-- Recurrent circuit with an emitted channel symbol at each state. -/
structure RecurrentCircuit (Sig : Type u) where
  State : Type v
  step : State → Sig → State
  emit : State → Sig

/-- Two recurrent circuits coupled through a shared symbol and merge rule. -/
structure CoupledConversation (Sig : Type u) where
  A : RecurrentCircuit Sig
  B : RecurrentCircuit Sig
  merge : Sig → Sig → Sig

/-- Joint state of a coupled conversation system. -/
structure JointState {Sig : Type u} (C : CoupledConversation Sig) where
  aState : C.A.State
  bState : C.B.State
  shared : Sig

/-- One coupled tick: both circuits consume the current shared symbol;
the next shared symbol is merged from both emissions. -/
def tick {Sig : Type u} (C : CoupledConversation Sig) (x : JointState C) : JointState C where
  aState := C.A.step x.aState x.shared
  bState := C.B.step x.bState x.shared
  shared := C.merge (C.A.emit x.aState) (C.B.emit x.bState)

/-- Coupling fact: both updates are driven by the same current shared symbol. -/
theorem tick_uses_shared_node
    {Sig : Type u} (C : CoupledConversation Sig) (x : JointState C) :
    (tick C x).aState = C.A.step x.aState x.shared ∧
      (tick C x).bState = C.B.step x.bState x.shared := by
  constructor <;> rfl

/-- Next shared symbol is computed from both circuit emissions. -/
theorem tick_shared_is_merged_emissions
    {Sig : Type u} (C : CoupledConversation Sig) (x : JointState C) :
    (tick C x).shared = C.merge (C.A.emit x.aState) (C.B.emit x.bState) := by
  rfl

/-! ## Bounded channel observability -/

/-- A bounded one-bit readout channel from `α` to discrete observable output. -/
structure BoundedChannel (α : Type u) where
  quantize : α → Bool

/-- Observer induced by channel quantization. -/
def channelObserver (C : BoundedChannel α) : ObserverClass α Bool where
  observe := C.quantize

/-- Observer quotient equality is exactly quantized-output equality. -/
theorem channel_projection_eq_iff_quantized_eq
    (C : BoundedChannel α) (x y : α) :
    project (channelObserver C) x = project (channelObserver C) y ↔
      C.quantize x = C.quantize y := by
  exact ObserverRelativeState.project_eq_iff (O := channelObserver C) x y

/-! ## Real-to-discrete clamp as decision operator -/

/-- Clamp real signal to one bit at threshold `τ`. -/
noncomputable def clampBit (τ sample : ℝ) : Bool :=
  decide (sample ≥ τ)

/-- Channel induced by threshold clamp. -/
noncomputable def clampChannel (τ : ℝ) : BoundedChannel ℝ where
  quantize := clampBit τ

/-- Clamp output is discrete by construction (`Bool`). -/
theorem clamp_output_is_discrete (τ sample : ℝ) :
    clampBit τ sample = true ∨ clampBit τ sample = false := by
  cases h : clampBit τ sample <;> simp

/-- Through a clamp channel, only clamped (quantized) state is observable. -/
theorem clamp_projection_eq_iff_same_clamped_bit
    (τ x y : ℝ) :
    project (channelObserver (clampChannel τ)) x =
      project (channelObserver (clampChannel τ)) y ↔
      clampBit τ x = clampBit τ y := by
  simpa [clampChannel, channelObserver] using
    (ObserverRelativeState.project_eq_iff
      (O := channelObserver (clampChannel τ)) x y)

/-- A clamp decision event is a change in the clamped bit between two samples. -/
noncomputable def clampDecisionEvent (τ xPrev xNext : ℝ) : Prop :=
  clampBit τ xNext ≠ clampBit τ xPrev

/-- One-bit lower bound generated by clamp change (0 if unchanged, 1 if changed). -/
noncomputable def clampDecisionBitOps (τ xPrev xNext : ℝ) : ℕ :=
  if clampBit τ xNext = clampBit τ xPrev then 0 else 1

/-- Clamp change yields a positive irreversible-bit lower bound. -/
theorem clampDecisionBitOps_pos_of_event
    {τ xPrev xNext : ℝ}
    (hEvent : clampDecisionEvent τ xPrev xNext) :
    0 < clampDecisionBitOps τ xPrev xNext := by
  unfold clampDecisionEvent at hEvent
  simp [clampDecisionBitOps, hEvent]

/-- Clamp-change event is equivalent to positive one-bit lower bound. -/
theorem clampDecisionEvent_iff_bitOps_pos
    (τ xPrev xNext : ℝ) :
    clampDecisionEvent τ xPrev xNext ↔ 0 < clampDecisionBitOps τ xPrev xNext := by
  by_cases hEq : clampBit τ xNext = clampBit τ xPrev
  · simp [clampDecisionEvent, clampDecisionBitOps, hEq]
  · simp [clampDecisionEvent, clampDecisionBitOps, hEq]

/-- Thermodynamic consequence: clamp-change event implies positive energy
lower bound under positive per-bit conversion. -/
theorem clamp_event_implies_positive_energy
    (M : ThermoModel)
    (hJ : 0 < M.joulesPerBit)
    {τ xPrev xNext : ℝ}
    (hEvent : clampDecisionEvent τ xPrev xNext) :
    0 < energyLowerBound M (clampDecisionBitOps τ xPrev xNext) := by
  apply energy_lower_mandatory M hJ
  exact clampDecisionBitOps_pos_of_event hEvent

/-! ## YES/NO/ABSTAIN report surface with explanation gap -/

/-- Binary answer token for non-abstaining outputs. -/
inductive BinaryAnswer
  | yes
  | no
  deriving DecidableEq, Repr

/-- Conversation-facing report:
`none` means ABSTAIN; `some yes/no` means YES/NO. -/
structure ConversationReport where
  answer : Option BinaryAnswer
  explanationBits : Nat
  declaredBudget : Nat

/-- Explanation gap under a declared bit budget. -/
def explanationGap (r : ConversationReport) : Nat :=
  r.declaredBudget - r.explanationBits

/-- If explanation bits are budget-feasible, gap + used = budget. -/
theorem explanationGap_add_explanationBits
    (r : ConversationReport)
    (hLe : r.explanationBits ≤ r.declaredBudget) :
    explanationGap r + r.explanationBits = r.declaredBudget := by
  unfold explanationGap
  exact Nat.sub_add_cancel hLe

/-- Bridge to typed claim reports:
YES/NO map to `.exact`, ABSTAIN maps to `.abstain`. -/
def toClaimReport (r : ConversationReport) : ClaimReport :=
  match r.answer with
  | none => ClaimReport.abstain
  | some _ => ClaimReport.exact

theorem abstain_iff_no_answer (r : ConversationReport) :
    toClaimReport r = ClaimReport.abstain ↔ r.answer = none := by
  cases h : r.answer <;> simp [toClaimReport, h]

theorem yes_no_iff_exact_claim (r : ConversationReport) :
    (∃ b : BinaryAnswer, r.answer = some b) ↔
      toClaimReport r = ClaimReport.exact := by
  cases h : r.answer with
  | none =>
      simp [toClaimReport, h]
  | some b =>
      simp [toClaimReport, h]

theorem toClaimReport_ne_epsilon (r : ConversationReport) (ε : ℝ) :
    toClaimReport r ≠ ClaimReport.epsilon ε := by
  cases h : r.answer <;> simp [toClaimReport, h]

/-- Canonical embedding into the existing typed report signal object. -/
def toReportSignal (r : ConversationReport) : ReportSignal BinaryAnswer where
  report := toClaimReport r
  guess := r.answer
  selfPct := percentZero
  certifiedPct := percentZero
  stepsRun := r.explanationBits
  declaredBound := some r.declaredBudget

theorem toReportSignal_declares_bound (r : ConversationReport) :
    (toReportSignal r).declaredBound = some r.declaredBudget := by
  rfl

theorem toReportSignal_completion_defined_of_budget
    (r : ConversationReport)
    (hPos : 0 < r.declaredBudget)
    (hLe : r.explanationBits ≤ r.declaredBudget) :
    CompletionFractionDefined (toReportSignal r) := by
  exact completion_fraction_defined_of_declared_bound
    (σ := toReportSignal r) (b := r.declaredBudget) rfl hPos hLe

/-- Zero certified confidence makes signal-consistency vacuous. -/
theorem toReportSignal_signal_consistent_zero_certified
    {X : Type*} {W : Type*}
    (R : Set (X × BinaryAnswer))
    (Rε : EpsilonRelation X BinaryAnswer)
    (Γ : Regime X)
    (Q : CertifyingSolver X BinaryAnswer W)
    (r : ConversationReport) :
    SignalConsistent R Rε Γ Q (toReportSignal r) := by
  intro hPos
  simp [toReportSignal, percentZero] at hPos

/-- ABSTAIN can still carry explicit explanation payload under this model. -/
theorem abstain_report_can_carry_explanation (k b : Nat) :
    ∃ r : ConversationReport,
      r.answer = none ∧ r.explanationBits = k ∧ r.declaredBudget = b := by
  refine ⟨{ answer := none, explanationBits := k, declaredBudget := b }, ?_, ?_, ?_⟩
  · rfl
  · rfl
  · rfl

end Conversation
end Physics
end DecisionQuotient
