"""Canonical CellProfiler module-name constants used by runtime policies."""

CELLPROFILER_MASK_IMAGE_MODULE = "MaskImage"
CELLPROFILER_RELATE_OBJECTS_MODULE = "RelateObjects"
CELLPROFILER_TRACK_OBJECTS_MODULE = "TrackObjects"
CELLPROFILER_CROP_MODULE = "Crop"
CELLPROFILER_CORRECT_ILLUMINATION_APPLY_MODULE = "CorrectIlluminationApply"
CELLPROFILER_CORRECT_ILLUMINATION_CALCULATE_MODULE = "CorrectIlluminationCalculate"
CELLPROFILER_CONVERT_OBJECTS_TO_IMAGE_MODULE = "ConvertObjectsToImage"
CELLPROFILER_MEASURE_OBJECT_SIZE_SHAPE_MODULE = "MeasureObjectSizeShape"
CELLPROFILER_MEASURE_OBJECT_INTENSITY_MODULE = "MeasureObjectIntensity"
CELLPROFILER_MEASURE_OBJECT_INTENSITY_DISTRIBUTION_MODULE = (
    "MeasureObjectIntensityDistribution"
)
CELLPROFILER_MEASURE_TEXTURE_MODULE = "MeasureTexture"
CELLPROFILER_MEASURE_COLOCALIZATION_MODULE = "MeasureColocalization"
CELLPROFILER_MEASURE_GRANULARITY_MODULE = "MeasureGranularity"
CELLPROFILER_MEASURE_OBJECT_NEIGHBORS_MODULE = "MeasureObjectNeighbors"
