"""Materialization public API (writer-based)."""

from openhcs.processing.materialization.constants import MaterializationFormat, WriteMode
from openhcs.processing.materialization.core import (
    BackendSaver,
    MaterializationContext,
    MaterializationSpec,
    Output,
    PathHelper,
    materialize,
    materialization_outputs,
    registered_materialization_option_types,
    tabular_field_names_from_materialization,
)
from openhcs.processing.materialization.options import (
    CsvOptions,
    FileBundleOptions,
    FileOutputOptions,
    ImageFileOptions,
    JsonOptions,
    MaterializedFilenameIdentity,
    ROIOptions,
    SpatialGraphROIOptions,
    SWCOptions,
    TextOptions,
    TiffStackOptions,
)
from openhcs.processing.materialization.presets import (
    csv_dataclass_materializer,
    csv_materializer,
    csv_only,
    json_and_csv,
    json_materializer,
    json_only,
    roi_zip,
    segmentation_mask_rois,
    text_only,
    tiff_stack,
)
__all__ = [
    "MaterializationFormat",
    "WriteMode",
    "MaterializationSpec",
    "MaterializationContext",
    "Output",
    "PathHelper",
    "BackendSaver",
    "materialize",
    "materialization_outputs",
    "registered_materialization_option_types",
    "FileOutputOptions",
    "ImageFileOptions",
    "FileBundleOptions",
    "MaterializedFilenameIdentity",
    "CsvOptions",
    "JsonOptions",
    "ROIOptions",
    "SpatialGraphROIOptions",
    "SWCOptions",
    "TiffStackOptions",
    "TextOptions",
    "csv_materializer",
    "csv_dataclass_materializer",
    "json_materializer",
    "json_only",
    "csv_only",
    "json_and_csv",
    "roi_zip",
    "segmentation_mask_rois",
    "tiff_stack",
    "text_only",
    "tabular_field_names_from_materialization",
]
