"""Materialization public API (writer-based)."""

from openhcs.processing.materialization.constants import MaterializationFormat, WriteMode
from openhcs.processing.materialization.core import (
    BackendSaver,
    MaterializationContext,
    MaterializationSpec,
    Output,
    PathHelper,
    materialize,
    tabular_field_names_from_materialization,
)
from openhcs.processing.materialization.options import (
    CsvOptions,
    FileOutputOptions,
    JsonOptions,
    MaterializedFilenameIdentity,
    ROIOptions,
    TextOptions,
    TiffStackOptions,
)
from openhcs.processing.materialization.presets import (
    csv_dataclass_materializer,
    csv_materializer,
    csv_only,
    json_and_csv,
    json_materializer,
    json_only,
    roi_zip,
    segmentation_mask_rois,
    text_only,
    tiff_stack,
)
__all__ = [
    "MaterializationFormat",
    "WriteMode",
    "MaterializationSpec",
    "MaterializationContext",
    "Output",
    "PathHelper",
    "BackendSaver",
    "materialize",
    "FileOutputOptions",
    "MaterializedFilenameIdentity",
    "CsvOptions",
    "JsonOptions",
    "ROIOptions",
    "TiffStackOptions",
    "TextOptions",
    "csv_materializer",
    "csv_dataclass_materializer",
    "json_materializer",
    "json_only",
    "csv_only",
    "json_and_csv",
    "roi_zip",
    "segmentation_mask_rois",
    "tiff_stack",
    "text_only",
    "tabular_field_names_from_materialization",
]
