name: Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode'
        required: true
        default: 'cpu-only'
        type: choice
        options:
        - cpu-only
        - full-coverage

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        backend: [disk, zarr]
        microscope: [ImageXpress, OperaPhenix]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run CPU-only integration tests
        if: github.event.inputs.test_mode == 'cpu-only' || github.event.inputs.test_mode == ''
        env:
          OPENHCS_CPU_ONLY: true
        run: |
          python -m pytest tests/integration/ \
                --it-backends ${{ matrix.backend }} \
                --it-microscopes ${{ matrix.microscope }} \
                --it-dims 3d \
                --it-exec-mode multiprocessing \
                -v --tb=short

      - name: Run full coverage integration tests
        if: github.event.inputs.test_mode == 'full-coverage'
        run: |
          python -m pytest tests/integration/ \
                --it-backends ${{ matrix.backend }} \
                --it-microscopes ${{ matrix.microscope }} \
                --it-dims all \
                --it-exec-mode all \
                -v --tb=short

  integration-tests-focused:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run focused CPU-only integration tests (default 4 combinations)
        env:
          OPENHCS_CPU_ONLY: true
        run: |
          python -m pytest tests/integration/ \
                --it-backends disk,zarr \
                --it-microscopes ImageXpress,OperaPhenix \
                --it-dims 3d \
                --it-exec-mode multiprocessing \
                -v --tb=short
