-- Auto-generated by build_papers.py -- do not edit
import DependencyGraph
import Paper1IT.BudgetSplit
import Paper1IT.ComputabilityQuantization
import Paper1IT.Entropy
import Paper1IT.EntropyGeneral
import Paper1IT.FanoFinite
import Paper1IT.FiberAllocation
import Paper1IT.FiberRateDistortion
import Paper1IT.FiniteRateDistortionBounds
import Paper1IT.FiniteRateDistortionConverse
import Paper1IT.FiniteSource
import Paper1IT.GraphEntropy
import Paper1IT.GraphEntropyAsymptotic
import Paper1IT.GrowthCollisions
import Paper1IT.GrowthTagBudget
import Paper1IT.ObserverTagModel
import Paper1IT.PMFEntropy
import Paper1IT.ProbabilisticFinite
import Paper1IT.QueryBitBridge
import Paper1IT.RateDistortion
import Paper1IT.ZeroErrorConditionalEntropy

#export_decl_info_json "decls.json"
